[project]
name = "pybalboa"
description = "Module to communicate with a Balboa spa wifi adapter."
authors = [
    { name = "Nathan Spencer", email = "natekspencer@gmail.com" },
    { name = "Tim Rightnour", email = "root@garbled.net" },
]
requires-python = ">=3.11"
readme = "README.md"
keywords = [
    "Balboa",
    "spa",
    "hot tub",
    "asynchronous",
]
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version"]
dependencies = []

[project.urls]
Homepage = "https://github.com/garbled1/pybalboa"
Repository = "https://github.com/garbled1/pybalboa"

[dependency-groups]
dev = [
    "pytest>=7.2.2,<10.0.0",
    "pytest-asyncio>=1.0.0",
    "pytest-cov>=4,<8",
    "pytest-timeout>=2.1.0,<3",
    "mypy>=1.3,<3",
    "tox>=3.26,<5.0",
    "ruff>=0.16.10",
    "pre-commit>=4.6.2",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.version]
path = "pybalboa/__init__.py"
pattern = true

[tool.hatch.build.targets.sdist]
include = ["pybalboa"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true }}]

[tool.uv-dynamic-versioning]
pattern = "default-unprefixed"
